package handler

import (
	"context"
	"errors"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sync"
	"time"

	"nginx-proxy-guard/internal/model"
	"nginx-proxy-guard/internal/nginx"
)

// Raw nginx log files: the settings that turn them on, the config the nginx
// entrypoint reads, and logrotate.
//
// Split out of system_settings.go, which had grown past the 500-line handler
// ceiling in api/CLAUDE.md. Pure move — the request handlers that call these
// stay where they were; what lives here is the machinery they drive.

// rawLogPaths are the files applying the raw log settings maintains, on the
// volume the API shares with the nginx container (defaultRawLogPaths).
type rawLogPaths struct {
	nginxConf string // 00-raw-logging.conf: the access_raw.log directive
	marker    string // .raw_log_config: what the nginx entrypoint renders from
	logrotate string // the logrotate stanza each rotation installs
	logsDir   string // the raw log files
}

var defaultRawLogPaths = rawLogPaths{
	nginxConf: "/etc/nginx/conf.d/00-raw-logging.conf",
	marker:    rawLogConfigFile,
	logrotate: nginx.LogrotateConfigPath,
	logsDir:   nginxLogsPath,
}

// rawLogFiles returns where this handler writes: the shared volume, unless a
// test pointed it elsewhere.
func (h *SystemSettingsHandler) rawLogFiles() rawLogPaths {
	if h.rawLogOverride != nil {
		return *h.rawLogOverride
	}
	return defaultRawLogPaths
}

// initRawLogSettings applies raw log settings if enabled
// This ensures settings are applied even after container restart
func (h *SystemSettingsHandler) initRawLogSettings() {
	ctx := context.Background()
	settings, err := h.repo.Get(ctx)
	if err != nil {
		log.Printf("[RawLog] Warning: failed to get settings on init: %v", err)
		return
	}

	if settings.RawLogEnabled {
		log.Printf("[RawLog] Raw logging is enabled, applying settings on startup...")
		if err := h.applyRawLogSettings(settings); err != nil {
			log.Printf("[RawLog] Warning: failed to apply raw log settings on init: %v", err)
		}
	}
}

// writeRawLogMarker writes .raw_log_config, the nginx entrypoint's copy of
// the raw log settings: whenever the nginx container starts, the entrypoint
// renders 00-raw-logging.conf when the file's ENABLED line reads true, and
// removes it otherwise — also when the file is missing. Every apply writes it,
// the one at API start-up included. Written only on a settings save, as it
// used to be, an install that never saved them lost raw logging (the log
// collector's source) whenever the nginx container restarted on its own.
// The file is written under a temporary name and renamed into place, so the
// entrypoint never reads half of it; the temporary name does not end in
// .conf, which nginx would include.
func writeRawLogMarker(path string, settings *model.SystemSettings) error {
	body := fmt.Sprintf(`# Raw Log Configuration
# Auto-generated by API - do not edit manually
# Last updated: %s

ENABLED=%t
MAX_SIZE_MB=%d
ROTATE_COUNT=%d
RETENTION_DAYS=%d
COMPRESS=%t
`,
		time.Now().Format(time.RFC3339),
		settings.RawLogEnabled,
		settings.RawLogMaxSizeMB,
		settings.RawLogRotateCount,
		settings.RawLogRetentionDays,
		settings.RawLogCompressRotated,
	)
	tmp, err := os.CreateTemp(filepath.Dir(path), ".raw_log_config-*.tmp")
	if err != nil {
		return fmt.Errorf("failed to write raw log config: %w", err)
	}
	defer os.Remove(tmp.Name()) // no-op after the rename
	_, werr := tmp.WriteString(body)
	cherr := tmp.Chmod(0644)
	serr := tmp.Sync()
	clerr := tmp.Close()
	if err := errors.Join(werr, cherr, serr, clerr); err != nil {
		return fmt.Errorf("failed to write raw log config: %w", err)
	}
	if err := os.Rename(tmp.Name(), path); err != nil {
		return fmt.Errorf("failed to write raw log config: %w", err)
	}
	return nil
}

// EnsureRawLogEnabled is the v2.17.1 boot-time guarantee that raw log storage
// is on. LogCollector switched to file-tail in v2.14.2 and depends on
// /etc/nginx/logs/access_raw.log; if raw_log_enabled was off from an older
// install the file is never created and access logs silently disappear
// (issue #145). Called from bootstrap.startBackgroundServices before the
// collector spins up.
func (h *SystemSettingsHandler) EnsureRawLogEnabled(ctx context.Context) error {
	settings, err := h.repo.Get(ctx)
	if err != nil {
		return fmt.Errorf("load system settings: %w", err)
	}
	if settings.RawLogEnabled {
		return nil
	}
	log.Printf("[SystemSettings] Auto-enabling raw log storage (was off); required by LogCollector since v2.17.1.")
	t := true
	updated, err := h.repo.Update(ctx, &model.UpdateSystemSettingsRequest{RawLogEnabled: &t})
	if err != nil {
		return fmt.Errorf("update system settings: %w", err)
	}
	return h.applyRawLogSettings(updated)
}

// ForceEnableRawLog unconditionally re-applies raw-log config: it ensures the
// DB flag is on AND always regenerates 00-raw-logging.conf, then reloads nginx
// (nginx -t first, via TestAndReload) — which reopens/recreates access_raw.log.
// Unlike EnsureRawLogEnabled (a boot no-op when the flag is already true), this
// always re-applies — the pipeline-canary auto-heal needs it because the
// conf/file can be missing even though the flag is true.
func (h *SystemSettingsHandler) ForceEnableRawLog(ctx context.Context) error {
	settings, err := h.repo.Get(ctx)
	if err != nil {
		return fmt.Errorf("load system settings: %w", err)
	}
	if !settings.RawLogEnabled {
		t := true
		settings, err = h.repo.Update(ctx, &model.UpdateSystemSettingsRequest{RawLogEnabled: &t})
		if err != nil {
			return fmt.Errorf("update system settings: %w", err)
		}
	}
	return h.applyRawLogSettings(settings)
}

// applyRawLogSettings creates/removes raw log files and nginx config immediately,
// and records the settings for the nginx entrypoint (writeRawLogMarker). Every
// change of the raw log settings goes through here: start-up, a settings save
// and the pipeline canary's repair.
func (h *SystemSettingsHandler) applyRawLogSettings(settings *model.SystemSettings) error {
	files := h.rawLogFiles()
	nginxContainer := os.Getenv("NGINX_CONTAINER")
	if nginxContainer == "" {
		nginxContainer = "npg-proxy"
	}

	if settings.RawLogEnabled {
		// Create nginx config for dual logging (on shared volume)
		nginxConfig := `# Raw log file storage (in addition to stdout/stderr)
# Auto-generated by API - do not edit manually
# Logs stored in /etc/nginx/logs for API access via consolidated volume

# Additional access log to file (main format)
# Buffer reduces disk I/O: 64k buffer, flush every 5 seconds
access_log /etc/nginx/logs/access_raw.log main buffer=64k flush=5s;

# Note: error_log can only have one destination in nginx main context
# For error logs, we log to both via Dockerfile symlink trick is not possible
# Error logs are captured from stderr which goes to error.log -> /dev/stderr
`
		if err := os.WriteFile(files.nginxConf, []byte(nginxConfig), 0644); err != nil {
			return fmt.Errorf("failed to write raw logging nginx config: %w", err)
		}

		// Generate logrotate configuration in shared volume
		if err := h.generateLogrotateConfig(settings); err != nil {
			log.Printf("[RawLog] Warning: failed to generate logrotate config: %v", err)
			// Continue - logrotate is not critical for basic operation
		}

		log.Printf("[RawLog] Raw logging enabled - config and files created")
	} else {
		// Remove raw logging config
		os.Remove(files.nginxConf)
		// Note: We don't delete the raw log files - user may want to keep historical data
		log.Printf("[RawLog] Raw logging disabled - nginx config removed")
	}
	// The running nginx gets the change from the reload below; this file is
	// what the nginx container starts from next time.
	if err := writeRawLogMarker(files.marker, settings); err != nil {
		log.Printf("[RawLog] Warning: %v; a restart of the nginx container alone would follow the previous copy, or turn raw logging off without one", err)
	}

	// Reload nginx to apply changes (nginx -t first, rollback on failure)
	if h.nginxManager != nil {
		ctx := context.Background()
		if err := h.nginxManager.TestAndReload(ctx); err != nil {
			return fmt.Errorf("failed to reload nginx: %w", err)
		}
		log.Printf("[RawLog] Nginx tested and reloaded successfully")
	}

	return nil
}

// generateLogrotateConfig writes the raw-log logrotate stanza to the shared
// volume (nginx.LogrotateConfigPath). nginx.Manager.RotateLogs installs it in
// the nginx container on every run, so nothing else needs to copy it there.
// The stanza itself — daily + maxsize, maxage as the retention, rotate as a
// safety cap — is documented in nginx/logrotate_config.go.
func (h *SystemSettingsHandler) generateLogrotateConfig(settings *model.SystemSettings) error {
	files := h.rawLogFiles()
	// Archives named before the dateformat carried a time are renamed into
	// the timestamped scheme first; logrotate's maxage globs only names its
	// own dateformat could have produced.
	migrateLegacyRotatedNamesIn(files.logsDir)

	rot, clamped := settings.EffectiveRawLogRotation()
	if clamped {
		logRawLogClampOnce(settings, rot)
	}
	if err := nginx.WriteLogrotateConfig(files.logrotate, files.logsDir, rot); err != nil {
		return fmt.Errorf("failed to write logrotate config: %w", err)
	}
	return nil
}

var rawLogClampLogged struct {
	sync.Mutex
	last string
}

// logRawLogClampOnce reports, once per distinct stored value, that a stored
// raw-log value logrotate cannot use was replaced in the rendering.
func logRawLogClampOnce(settings *model.SystemSettings, used model.RawLogRotation) {
	key := fmt.Sprintf("%d/%d", settings.RawLogRetentionDays, settings.RawLogMaxSizeMB)
	rawLogClampLogged.Lock()
	defer rawLogClampLogged.Unlock()
	if rawLogClampLogged.last == key {
		return
	}
	rawLogClampLogged.last = key
	log.Printf("[RawLog] Stored raw log settings (retention %d days, max size %d MB) are outside what logrotate accepts; rotating with retention %d days and max size %d MB instead",
		settings.RawLogRetentionDays, settings.RawLogMaxSizeMB, used.RetentionDays, used.MaxSizeMB)
}

// legacyDatedArchive matches the rotated names produced before the dateformat
// grew a time component: access_raw.log-20260919, error_raw.log-20260919.gz.
var legacyDatedArchive = regexp.MustCompile(`^(access_raw|error_raw)\.log-([0-9]{8})(\.gz|\.bz2)?$`)

// migrateLegacyRotatedNamesIn renames those archives in dir into the
// timestamped scheme.
//
// logrotate prunes dateext archives by globbing the pattern its own dateformat
// implies, so the moment the format grew a time component the 8-digit names
// stopped matching it: `rotate N` would have counted only the new files and
// left every pre-upgrade archive on disk forever. Renaming them to midnight of
// the day they already carry is lossless (rename keeps the mtime), sorts
// exactly where it did before, and is idempotent — once renamed a name no
// longer matches the pattern. An archive that would collide with one already
// present is left alone rather than overwritten.
func migrateLegacyRotatedNamesIn(dir string) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		m := legacyDatedArchive.FindStringSubmatch(entry.Name())
		if m == nil {
			continue
		}
		target := filepath.Join(dir, fmt.Sprintf("%s.log-%s-000000%s", m[1], m[2], m[3]))
		if _, err := os.Stat(target); err == nil {
			continue
		}
		if err := os.Rename(filepath.Join(dir, entry.Name()), target); err != nil {
			log.Printf("[RawLog] Warning: could not rename legacy rotated log %s: %v", entry.Name(), err)
			continue
		}
		log.Printf("[RawLog] Renamed legacy rotated log %s -> %s", entry.Name(), filepath.Base(target))
	}
}
