package handler

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sync"
	"time"

	"nginx-proxy-guard/internal/model"
	"nginx-proxy-guard/internal/nginx"
)

// Raw nginx log files: the settings that turn them on, the config the nginx
// entrypoint reads, and logrotate.
//
// Split out of system_settings.go, which had grown past the 500-line handler
// ceiling in api/CLAUDE.md. Pure move — the request handlers that call these
// stay where they were; what lives here is the machinery they drive.

// initRawLogSettings applies raw log settings if enabled
// This ensures settings are applied even after container restart
func (h *SystemSettingsHandler) initRawLogSettings() {
	ctx := context.Background()
	settings, err := h.repo.Get(ctx)
	if err != nil {
		log.Printf("[RawLog] Warning: failed to get settings on init: %v", err)
		return
	}

	if settings.RawLogEnabled {
		log.Printf("[RawLog] Raw logging is enabled, applying settings on startup...")
		if err := h.applyRawLogSettings(settings); err != nil {
			log.Printf("[RawLog] Warning: failed to apply raw log settings on init: %v", err)
		}
	}
}

// generateRawLogConfig creates/updates the raw log configuration file
// that nginx entrypoint uses to configure log files
func (h *SystemSettingsHandler) generateRawLogConfig(settings *model.SystemSettings) error {
	config := fmt.Sprintf(`# Raw Log Configuration
# Auto-generated by API - do not edit manually
# Last updated: %s

ENABLED=%t
MAX_SIZE_MB=%d
ROTATE_COUNT=%d
RETENTION_DAYS=%d
COMPRESS=%t
`,
		time.Now().Format(time.RFC3339),
		settings.RawLogEnabled,
		settings.RawLogMaxSizeMB,
		settings.RawLogRotateCount,
		settings.RawLogRetentionDays,
		settings.RawLogCompressRotated,
	)

	// Write configuration file
	if err := os.WriteFile(rawLogConfigFile, []byte(config), 0644); err != nil {
		return fmt.Errorf("failed to write raw log config: %w", err)
	}

	// Apply raw log settings immediately (don't wait for container restart)
	if err := h.applyRawLogSettings(settings); err != nil {
		return fmt.Errorf("failed to apply raw log settings: %w", err)
	}

	return nil
}

// EnsureRawLogEnabled is the v2.17.1 boot-time guarantee that raw log storage
// is on. LogCollector switched to file-tail in v2.14.2 and depends on
// /etc/nginx/logs/access_raw.log; if raw_log_enabled was off from an older
// install the file is never created and access logs silently disappear
// (issue #145). Called from bootstrap.startBackgroundServices before the
// collector spins up.
func (h *SystemSettingsHandler) EnsureRawLogEnabled(ctx context.Context) error {
	settings, err := h.repo.Get(ctx)
	if err != nil {
		return fmt.Errorf("load system settings: %w", err)
	}
	if settings.RawLogEnabled {
		return nil
	}
	log.Printf("[SystemSettings] Auto-enabling raw log storage (was off); required by LogCollector since v2.17.1.")
	t := true
	updated, err := h.repo.Update(ctx, &model.UpdateSystemSettingsRequest{RawLogEnabled: &t})
	if err != nil {
		return fmt.Errorf("update system settings: %w", err)
	}
	return h.applyRawLogSettings(updated)
}

// ForceEnableRawLog unconditionally re-applies raw-log config: it ensures the
// DB flag is on AND always regenerates 00-raw-logging.conf, then reloads nginx
// (nginx -t first, via TestAndReload) — which reopens/recreates access_raw.log.
// Unlike EnsureRawLogEnabled (a boot no-op when the flag is already true), this
// always re-applies — the pipeline-canary auto-heal needs it because the
// conf/file can be missing even though the flag is true.
func (h *SystemSettingsHandler) ForceEnableRawLog(ctx context.Context) error {
	settings, err := h.repo.Get(ctx)
	if err != nil {
		return fmt.Errorf("load system settings: %w", err)
	}
	if !settings.RawLogEnabled {
		t := true
		settings, err = h.repo.Update(ctx, &model.UpdateSystemSettingsRequest{RawLogEnabled: &t})
		if err != nil {
			return fmt.Errorf("update system settings: %w", err)
		}
	}
	return h.applyRawLogSettings(settings)
}

// applyRawLogSettings creates/removes raw log files and nginx config immediately
func (h *SystemSettingsHandler) applyRawLogSettings(settings *model.SystemSettings) error {
	rawLoggingConf := "/etc/nginx/conf.d/00-raw-logging.conf"
	nginxContainer := os.Getenv("NGINX_CONTAINER")
	if nginxContainer == "" {
		nginxContainer = "npg-proxy"
	}

	if settings.RawLogEnabled {
		// Create nginx config for dual logging (on shared volume)
		nginxConfig := `# Raw log file storage (in addition to stdout/stderr)
# Auto-generated by API - do not edit manually
# Logs stored in /etc/nginx/logs for API access via consolidated volume

# Additional access log to file (main format)
# Buffer reduces disk I/O: 64k buffer, flush every 5 seconds
access_log /etc/nginx/logs/access_raw.log main buffer=64k flush=5s;

# Note: error_log can only have one destination in nginx main context
# For error logs, we log to both via Dockerfile symlink trick is not possible
# Error logs are captured from stderr which goes to error.log -> /dev/stderr
`
		if err := os.WriteFile(rawLoggingConf, []byte(nginxConfig), 0644); err != nil {
			return fmt.Errorf("failed to write raw logging nginx config: %w", err)
		}

		// Generate logrotate configuration in shared volume
		if err := h.generateLogrotateConfig(settings); err != nil {
			log.Printf("[RawLog] Warning: failed to generate logrotate config: %v", err)
			// Continue - logrotate is not critical for basic operation
		}

		log.Printf("[RawLog] Raw logging enabled - config and files created")
	} else {
		// Remove raw logging config
		os.Remove(rawLoggingConf)
		// Note: We don't delete the raw log files - user may want to keep historical data
		log.Printf("[RawLog] Raw logging disabled - nginx config removed")
	}

	// Reload nginx to apply changes (nginx -t first, rollback on failure)
	if h.nginxManager != nil {
		ctx := context.Background()
		if err := h.nginxManager.TestAndReload(ctx); err != nil {
			return fmt.Errorf("failed to reload nginx: %w", err)
		}
		log.Printf("[RawLog] Nginx tested and reloaded successfully")
	}

	return nil
}

// generateLogrotateConfig writes the raw-log logrotate stanza to the shared
// volume (nginx.LogrotateConfigPath). nginx.Manager.RotateLogs installs it in
// the nginx container on every run, so nothing else needs to copy it there.
// The stanza itself — daily + maxsize, maxage as the retention, rotate as a
// safety cap — is documented in nginx/logrotate_config.go.
func (h *SystemSettingsHandler) generateLogrotateConfig(settings *model.SystemSettings) error {
	// Archives named before the dateformat carried a time are renamed into
	// the timestamped scheme first; logrotate's maxage globs only names its
	// own dateformat could have produced.
	migrateLegacyRotatedNames()

	rot, clamped := settings.EffectiveRawLogRotation()
	if clamped {
		logRawLogClampOnce(settings, rot)
	}
	if err := nginx.WriteLogrotateConfig(nginx.LogrotateConfigPath, nginxLogsPath, rot); err != nil {
		return fmt.Errorf("failed to write logrotate config: %w", err)
	}
	return nil
}

var rawLogClampLogged struct {
	sync.Mutex
	last string
}

// logRawLogClampOnce reports, once per distinct stored value, that a stored
// raw-log value logrotate cannot use was replaced in the rendering.
func logRawLogClampOnce(settings *model.SystemSettings, used model.RawLogRotation) {
	key := fmt.Sprintf("%d/%d", settings.RawLogRetentionDays, settings.RawLogMaxSizeMB)
	rawLogClampLogged.Lock()
	defer rawLogClampLogged.Unlock()
	if rawLogClampLogged.last == key {
		return
	}
	rawLogClampLogged.last = key
	log.Printf("[RawLog] Stored raw log settings (retention %d days, max size %d MB) are outside what logrotate accepts; rotating with retention %d days and max size %d MB instead",
		settings.RawLogRetentionDays, settings.RawLogMaxSizeMB, used.RetentionDays, used.MaxSizeMB)
}

// legacyDatedArchive matches the rotated names produced before the dateformat
// grew a time component: access_raw.log-20260919, error_raw.log-20260919.gz.
var legacyDatedArchive = regexp.MustCompile(`^(access_raw|error_raw)\.log-([0-9]{8})(\.gz|\.bz2)?$`)

// migrateLegacyRotatedNames renames those archives into the timestamped scheme.
//
// logrotate prunes dateext archives by globbing the pattern its own dateformat
// implies, so the moment the format grew a time component the 8-digit names
// stopped matching it: `rotate N` would have counted only the new files and
// left every pre-upgrade archive on disk forever. Renaming them to midnight of
// the day they already carry is lossless (rename keeps the mtime), sorts
// exactly where it did before, and is idempotent — once renamed a name no
// longer matches the pattern. An archive that would collide with one already
// present is left alone rather than overwritten.
func migrateLegacyRotatedNames() { migrateLegacyRotatedNamesIn(nginxLogsPath) }

func migrateLegacyRotatedNamesIn(dir string) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		m := legacyDatedArchive.FindStringSubmatch(entry.Name())
		if m == nil {
			continue
		}
		target := filepath.Join(dir, fmt.Sprintf("%s.log-%s-000000%s", m[1], m[2], m[3]))
		if _, err := os.Stat(target); err == nil {
			continue
		}
		if err := os.Rename(filepath.Join(dir, entry.Name()), target); err != nil {
			log.Printf("[RawLog] Warning: could not rename legacy rotated log %s: %v", entry.Name(), err)
			continue
		}
		log.Printf("[RawLog] Renamed legacy rotated log %s -> %s", entry.Name(), filepath.Base(target))
	}
}
