package nginx

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

// Default server config template
const defaultServerTemplate = `# Default server - catch-all for unmatched requests
# Direct IP Access Action: {{.Action}}
# Generated by Nginx Proxy Guard

# HTTP default server
server {
    listen {{.HTTPPort}} default_server;
{{if .EnableIPv6}}    listen [::]:{{.HTTPPort}} default_server;
{{end}}    server_name _;

    # Disable WAF for default server (health check, ACME, etc.)
    modsecurity off;

    # Health check endpoint (always allowed)
    location /health {
        access_log off;
        return 200 'OK';
        add_header Content-Type text/plain;
    }

    # Nginx status endpoint (for API stats collection)
    location /nginx_status {
        stub_status;
        access_log off;
        allow 127.0.0.1;
        allow ::1;
        allow 172.16.0.0/12;
        allow 192.168.0.0/16;
        allow 10.0.0.0/8;
        deny all;
    }

    # ACME HTTP-01 Challenge support (for Let's Encrypt)
    location /.well-known/acme-challenge/ {
        root /etc/nginx/acme-challenge;
        try_files $uri =404;
    }

    # Internal pipeline canary (PipelineCanary service). Returns 204, internal
    # only. Deliberately declares NO access_log so it inherits the http-level
    # 00-raw-logging.conf directive — i.e. it logs to access_raw.log IFF real
    # traffic does. If raw logging is broken the canary correctly fails too.
    location = /__npg_canary {
        allow 127.0.0.1;
        allow ::1;
        allow 172.16.0.0/12;
        allow 192.168.0.0/16;
        allow 10.0.0.0/8;
        deny all;
        return 204;
    }

    # Custom error pages
    error_page 403 /403.html;
    error_page 502 /502.html;
    error_page 503 /503.html;
    error_page 504 /504.html;

    location = /403.html {
        root /etc/nginx/html;
        internal;
    }
    location = /502.html {
        root /etc/nginx/html;
        internal;
    }
    location = /503.html {
        root /etc/nginx/html;
        internal;
    }
    location = /504.html {
        root /etc/nginx/html;
        internal;
    }

    # Public API proxy (for font settings, etc.) - always available
    location /api/v1/public/ {
        proxy_pass {{.APIURL}}/api/v1/public/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

{{if eq .Action "block_444"}}
    # Cleartext HTTP spoken to an 'ssl' listener is finalized as nginx's
    # internal 497 before the content phase, so a bare 'return 444' in
    # 'location /' never sees it and the client gets '400 Bad Request / The
    # plain HTTP request was sent to HTTPS port' while the setting promises
    # 444. Measured on one install this was 52% of a week's unattributed 400s
    # (#280). error_page reaches it because r->srv_conf is initialised from the
    # listen socket's default_server before the request is parsed.
    #
    # Deliberately limited to 497. nginx also answers 400 for a request line it
    # could not parse at all (missing/duplicate Host, garbage method, non-HTTP
    # bytes) and 494 for oversized headers — but those are decided before the
    # Host header is read, so rescuing them would silently drop malformed
    # requests aimed at a hostname the operator HAS configured, trading a
    # diagnosable 400 for a silent reset. Those stay 400 and stay in the log.
    error_page 497 =444 /_npg_close;
    location = /_npg_close {
        internal;
        return 444;
    }
{{end}}

{{if eq .Action "block_444"}}
    # Block direct IP access - close connection without response
    location / {
        return 444;
    }
{{else if eq .Action "block_403"}}
    # Block direct IP access - return 403 Forbidden with custom page
    location / {
        return 403;
    }
{{else}}
    # Allow direct IP access - show Nginx Proxy Guard welcome page
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
{{end}}
}

# HTTPS default server - reject SSL handshake for unknown/disabled hosts
server {
    listen {{.HTTPSPort}} ssl default_server;
{{if .EnableIPv6}}    listen [::]:{{.HTTPSPort}} ssl default_server;
{{end}}    server_name _;

    # Reject SSL handshake immediately - no certificate warning, just connection reset
    ssl_reject_handshake on;

    # Direct handshakes to unknown SNI are rejected above. But a request can still
    # reach this default server by Host header over a connection whose TLS was
    # terminated by the loopback server below — i.e. Cloudflare Tunnel traffic for
    # a subdomain that has no configured proxy host. Apply the same Direct IP
    # Access Action so those non-existent subdomains are handled consistently
    # (e.g. silently closed with 444) instead of leaking the welcome page. (#212)
{{if eq .Action "block_444"}}
    # Cleartext HTTP spoken to an 'ssl' listener is finalized as nginx's
    # internal 497 before the content phase, so a bare 'return 444' in
    # 'location /' never sees it and the client gets '400 Bad Request / The
    # plain HTTP request was sent to HTTPS port' while the setting promises
    # 444. Measured on one install this was 52% of a week's unattributed 400s
    # (#280). error_page reaches it because r->srv_conf is initialised from the
    # listen socket's default_server before the request is parsed.
    #
    # Deliberately limited to 497. nginx also answers 400 for a request line it
    # could not parse at all (missing/duplicate Host, garbage method, non-HTTP
    # bytes) and 494 for oversized headers — but those are decided before the
    # Host header is read, so rescuing them would silently drop malformed
    # requests aimed at a hostname the operator HAS configured, trading a
    # diagnosable 400 for a silent reset. Those stay 400 and stay in the log.
    error_page 497 =444 /_npg_close;
    location = /_npg_close {
        internal;
        return 444;
    }
{{end}}

{{if eq .Action "block_444"}}
    location / {
        return 444;
    }
{{else if eq .Action "block_403"}}
    location / {
        return 403;
    }
{{else}}
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files $uri $uri/ =404;
    }
{{end}}
}

# Loopback HTTPS server so the Cloudflare Tunnel connector (which reaches nginx
# over https://localhost, SNI "localhost") can complete the TLS handshake. The
# default server above still rejects every OTHER unknown SNI (scanners); only
# the loopback SNI is accepted here, using a self-signed cert generated by the
# nginx entrypoint. Real proxy hosts are selected by the Host header, so tunnel
# traffic is routed correctly; requests whose Host is literally localhost (no
# proxy host matched) are closed. (#209)
server {
    listen {{.HTTPSPort}} ssl;
{{if .EnableIPv6}}    listen [::]:{{.HTTPSPort}} ssl;
{{end}}    server_name localhost 127.0.0.1;

    ssl_certificate     /etc/nginx/certs/default-selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/default-selfsigned.key;

    # This block answers 444 unconditionally, so it takes the same 497 rescue
    # unconditionally — cleartext sent to the HTTPS port with a loopback or
    # IP-literal Host lands here and would otherwise answer 400 (#280).
    error_page 497 =444 /_npg_close;
    location = /_npg_close {
        internal;
        return 444;
    }

    return 444;
}
`

// DefaultServerConfigData holds data for default server config generation
type DefaultServerConfigData struct {
	Action    string // allow, block_403, block_444
	HTTPPort  string // HTTP listen port (default: 80)
	HTTPSPort string // HTTPS listen port (default: 443)
	APIURL     string // API URL for nginx to reach API (default: http://127.0.0.1:9080)
	EnableIPv6 bool
}

// GenerateDefaultServerConfig generates the default server config based on settings
func (m *Manager) GenerateDefaultServerConfig(ctx context.Context, action string) error {
	// Validate action
	if action != "allow" && action != "block_403" && action != "block_444" {
		action = "allow" // Default to allow if invalid
	}

	funcMap := GetSimpleTemplateFuncMap()

	tmpl, err := template.New("default_server").Funcs(funcMap).Parse(defaultServerTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse default server template: %w", err)
	}

	data := DefaultServerConfigData{
		Action:     action,
		HTTPPort:   m.httpPort,
		HTTPSPort:  m.httpsPort,
		APIURL:     m.apiURL,
		EnableIPv6: m.enableIPv6,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("failed to execute default server template: %w", err)
	}

	// Use zzz_ prefix to ensure this loads last (after proxy host configs)
	configFile := filepath.Join(m.configPath, "zzz_default.conf")
	
	// Use atomic write to prevent nginx from reading partial config
	if err := m.writeFileAtomic(configFile, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("failed to write default server config file: %w", err)
	}

	// Remove old default.conf if it exists (migration from old naming)
	oldConfigFile := filepath.Join(m.configPath, "default.conf")
	os.Remove(oldConfigFile) // Ignore error if doesn't exist

	return nil
}
