package nginx

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GenerateFilterSubscriptionIPsInclude generates a shared include file containing
// all filter subscription IP/CIDR entries. This file is included inside each host's
// geo block via nginx's geo include directive, avoiding duplication of 50k+ entries
// across every proxy host config.
//
// The file is written to conf.d/includes/filter_sub_ips.conf
func (m *Manager) GenerateFilterSubscriptionIPsInclude(ips []string) error {
	includesDir := filepath.Join(m.configPath, "includes")
	if err := os.MkdirAll(includesDir, 0755); err != nil {
		return fmt.Errorf("failed to create includes directory: %w", err)
	}

	var sb strings.Builder
	sb.WriteString("# Filter Subscription IPs - auto-generated by Nginx Proxy Guard\n")
	sb.WriteString("# DO NOT EDIT - this file is regenerated when filter subscriptions change\n")
	sb.WriteString(fmt.Sprintf("# Total entries: %d\n", len(ips)))

	for _, ip := range ips {
		sb.WriteString(fmt.Sprintf("    %s 1;\n", ip))
	}

	includePath := filepath.Join(includesDir, "filter_sub_ips.conf")
	if err := m.writeFileAtomic(includePath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write filter_sub_ips.conf: %w", err)
	}

	return nil
}

// GenerateFilterSubscriptionUAsConfig generates a shared map block for filter
// subscription User-Agent patterns. This is written as a complete nginx map block
// to conf.d/filter_sub_uas.conf and loaded globally by nginx.
//
// Each host template checks $filter_sub_ua_blocked to apply the filter.
func (m *Manager) GenerateFilterSubscriptionUAsConfig(uas []string) error {
	configPath := filepath.Join(m.configPath, "filter_sub_uas.conf")

	var sb strings.Builder
	sb.WriteString("# Filter Subscription User-Agents - auto-generated by Nginx Proxy Guard\n")
	sb.WriteString("# DO NOT EDIT - this file is regenerated when filter subscriptions change\n")
	sb.WriteString(fmt.Sprintf("# Total patterns: %d\n\n", len(uas)))

	sb.WriteString("map $http_user_agent $filter_sub_ua_blocked {\n")
	sb.WriteString("    default 0;\n")
	for _, ua := range uas {
		sb.WriteString(fmt.Sprintf("    \"~*%s\" 1;\n", ua))
	}
	sb.WriteString("}\n")

	if err := m.writeFileAtomic(configPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write filter_sub_uas.conf: %w", err)
	}

	return nil
}

// GenerateFilterSubscriptionConfigs generates both the shared IP include file
// and the UA map block. This should be called when filter subscription entries
// change (create, refresh, delete) instead of regenerating all host configs.
func (m *Manager) GenerateFilterSubscriptionConfigs(ips []string, uas []string) error {
	if err := m.GenerateFilterSubscriptionIPsInclude(ips); err != nil {
		return err
	}
	if err := m.GenerateFilterSubscriptionUAsConfig(uas); err != nil {
		return err
	}
	return nil
}
