package nginx

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
)

// EnsureFilterSubscriptionFiles creates placeholder filter subscription config files
// if they don't exist. This prevents nginx from failing with "file not found" errors
// when host configs reference these include files before any subscriptions are created.
func (m *Manager) EnsureFilterSubscriptionFiles() error {
	includesDir := filepath.Join(m.configPath, "includes")
	if err := os.MkdirAll(includesDir, 0755); err != nil {
		return fmt.Errorf("failed to create includes directory: %w", err)
	}

	ipsPath := filepath.Join(includesDir, "filter_sub_ips.conf")
	if _, err := os.Stat(ipsPath); os.IsNotExist(err) {
		placeholder := "# Filter Subscription IPs - auto-generated by Nginx Proxy Guard\n# No entries\n"
		if err := os.WriteFile(ipsPath, []byte(placeholder), 0644); err != nil {
			return fmt.Errorf("failed to create filter_sub_ips.conf placeholder: %w", err)
		}
	}

	uasPath := filepath.Join(m.configPath, "filter_sub_uas.conf")
	if _, err := os.Stat(uasPath); os.IsNotExist(err) {
		placeholder := "# Filter Subscription User-Agents - auto-generated by Nginx Proxy Guard\n# No entries\n\nmap $http_user_agent $filter_sub_ua_blocked {\n    default 0;\n}\n"
		if err := os.WriteFile(uasPath, []byte(placeholder), 0644); err != nil {
			return fmt.Errorf("failed to create filter_sub_uas.conf placeholder: %w", err)
		}
	}

	return nil
}

// GenerateFilterSubscriptionIPsInclude generates a shared include file containing
// all filter subscription IP/CIDR entries. This file is included inside each host's
// geo block via nginx's geo include directive, avoiding duplication of 50k+ entries
// across every proxy host config.
//
// The file is written to conf.d/includes/filter_sub_ips.conf
func (m *Manager) GenerateFilterSubscriptionIPsInclude(ips []string) error {
	includesDir := filepath.Join(m.configPath, "includes")
	if err := os.MkdirAll(includesDir, 0755); err != nil {
		return fmt.Errorf("failed to create includes directory: %w", err)
	}

	var sb strings.Builder
	sb.WriteString("# Filter Subscription IPs - auto-generated by Nginx Proxy Guard\n")
	sb.WriteString("# DO NOT EDIT - this file is regenerated when filter subscriptions change\n")
	sb.WriteString(fmt.Sprintf("# Total entries: %d\n", len(ips)))

	for _, ip := range ips {
		sb.WriteString(fmt.Sprintf("    %s 2;\n", ip))
	}

	includePath := filepath.Join(includesDir, "filter_sub_ips.conf")
	if err := m.writeFileAtomic(includePath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write filter_sub_ips.conf: %w", err)
	}

	return nil
}

// GenerateFilterSubscriptionUAsConfig generates a shared map block for filter
// subscription User-Agent patterns. This is written as a complete nginx map block
// to conf.d/filter_sub_uas.conf and loaded globally by nginx.
//
// Each host template checks $filter_sub_ua_blocked to apply the filter.
func (m *Manager) GenerateFilterSubscriptionUAsConfig(uas []string) error {
	configPath := filepath.Join(m.configPath, "filter_sub_uas.conf")

	var sb strings.Builder
	sb.WriteString("# Filter Subscription User-Agents - auto-generated by Nginx Proxy Guard\n")
	sb.WriteString("# DO NOT EDIT - this file is regenerated when filter subscriptions change\n")
	sb.WriteString(fmt.Sprintf("# Total patterns: %d\n\n", len(uas)))

	sb.WriteString("map $http_user_agent $filter_sub_ua_blocked {\n")
	sb.WriteString("    default 0;\n")
	for _, ua := range uas {
		sb.WriteString(fmt.Sprintf("    \"~*%s\" 1;\n", ua))
	}
	sb.WriteString("}\n")

	if err := m.writeFileAtomic(configPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write filter_sub_uas.conf: %w", err)
	}

	return nil
}

// GenerateFilterSubscriptionConfigs generates both the shared IP include file
// and the UA map block with nginx -t validation and automatic rollback on failure.
//
// Flow: backup → write → nginx -t → success: done / fail: rollback
func (m *Manager) GenerateFilterSubscriptionConfigs(ctx context.Context, ips []string, uas []string) error {
	return m.executeWithLock(ctx, func() error {
		ipsPath := filepath.Join(m.configPath, "includes", "filter_sub_ips.conf")
		uasPath := filepath.Join(m.configPath, "filter_sub_uas.conf")

		// 1. Backup existing files
		ipsBackup, ipsExists := readFileIfExists(ipsPath)
		uasBackup, uasExists := readFileIfExists(uasPath)

		// 2. Write new config files
		if err := m.GenerateFilterSubscriptionIPsInclude(ips); err != nil {
			return err
		}
		if err := m.GenerateFilterSubscriptionUAsConfig(uas); err != nil {
			// Rollback IPs
			rollbackFile(ipsPath, ipsBackup, ipsExists)
			return err
		}

		// 3. Test nginx configuration
		if err := m.testConfigInternal(ctx); err != nil {
			// nginx -t failed — rollback both files
			log.Printf("[FilterSubscription] nginx -t failed, rolling back filter configs: %v", err)
			rollbackFile(ipsPath, ipsBackup, ipsExists)
			rollbackFile(uasPath, uasBackup, uasExists)
			return fmt.Errorf("nginx config test failed after filter update: %w", err)
		}

		return nil
	})
}

func readFileIfExists(path string) ([]byte, bool) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, false
	}
	return content, true
}

func rollbackFile(path string, backup []byte, existed bool) {
	if existed {
		if err := os.WriteFile(path, backup, 0644); err != nil {
			log.Printf("[FilterSubscription] Failed to rollback %s: %v", path, err)
		}
	}
	// If file didn't exist before, keep the newly written file instead of deleting it.
	// Deleting include files that host configs reference causes nginx to become inoperable.
}
