package nginx

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
)

// hostCommonIncludeContent renders the shared per-server stanza included by
// every generated proxy host server block (HTTP and HTTPS) — resolver,
// ACME/challenge security-skip variables, and the custom error pages. Factoring
// it out of base.conf.tmpl / ssl.conf.tmpl keeps the stanza in ONE place
// instead of two byte-identical copies per host, so nginx parses it once per
// server instead of carrying the duplicated text in every generated file.
//
// The per-server open_file_cache block that used to live in this stanza was
// dropped entirely: the API-generated main nginx.conf already emits the same
// GlobalSettings-derived values at http level (main_config.go), which server
// blocks inherit.
//
// The file is API-owned and lives in conf.d/includes/ (NOT auto-loaded by
// nginx — it contains server-context directives and is only pulled in via the
// per-host `include` line).
func (m *Manager) hostCommonIncludeContent() []byte {
	return []byte(fmt.Sprintf(`# Shared proxy-host server stanza - auto-generated by Nginx Proxy Guard
# DO NOT EDIT - included by every generated proxy host server block

# Resolver for dynamic proxy_pass with variables
resolver %s valid=30s;

# Skip security checks for ACME HTTP-01 Challenge
set $skip_security_for_acme 0;
if ($request_uri ~ "^/.well-known/acme-challenge/") {
    set $skip_security_for_acme 1;
}
# Also skip for challenge page to prevent redirect loops
if ($request_uri ~ "^/api/v1/challenge/") {
    set $skip_security_for_acme 1;
}

# Custom error pages for upstream errors
error_page 502 /error_502.html;
error_page 503 /error_503.html;
error_page 504 /error_504.html;
location = /error_502.html { internal; root /etc/nginx/html; try_files /502.html =502; }
location = /error_503.html { internal; root /etc/nginx/html; try_files /503.html =503; }
location = /error_504.html { internal; root /etc/nginx/html; try_files /504.html =504; }

# Custom error page for security blocks (WAF, block_exploits, geo restriction, bot filter, etc.)
error_page 403 @blocked;
location @blocked {
    root /etc/nginx/html;
    default_type text/html;
    try_files /403.html =403;
}
`, m.dnsResolver))
}

// ensureHostCommonInclude writes conf.d/includes/host_common.conf when missing
// or stale (e.g. DNS_RESOLVER changed across restarts). It is called from
// GenerateConfigFull BEFORE the host config that references it is written, so
// the include always exists first — including on fresh installs and after
// volume wipes. Content only changes with the manager's resolver, so this is a
// read+compare no-op on the hot path.
func (m *Manager) ensureHostCommonInclude() error {
	path := filepath.Join(m.configPath, "includes", "host_common.conf")
	desired := m.hostCommonIncludeContent()
	if current, err := os.ReadFile(path); err == nil && bytes.Equal(current, desired) {
		return nil
	}
	return m.writeFileAtomic(path, desired, 0644)
}
