package nginx

import (
	"fmt"
	"os"
	"path/filepath"

	"nginx-proxy-guard/internal/model"
)

// The raw-log logrotate stanza.
//
// Retention is by age: `maxage <retention days>` deletes rotated files older
// than that at the next rotation (logrotate checks age only when it rotates,
// and by mtime). `rotate` is only a safety cap. It cannot be the retention:
// once the live file is also cut when it passes maxsize (hourly checks, see
// scheduler.LogRotateScheduler), any small count deletes files inside the
// maxage window, and `rotate 0` deletes each file the moment it is rotated.
//
// `daily` + `maxsize` keeps one cut per day and adds an early cut for a large
// file. The former `daily` + `size` made the stanza size-only: a non-forced
// run never rotated on a day change, and the forced midnight run ignored the
// size, which is how one day's file reached 2.7 GB.
//
// The time in dateformat is load-bearing (#301): logrotate refuses to rotate
// onto a name that already exists, so a date-only suffix let one rotation per
// day claim the name. Second precision gives every rotation its own name and
// keeps the names sorted.
//
// delaycompress stays: nginx reopens its logs asynchronously after the
// postrotate USR1, and the newest rotated file can still receive its last
// buffered lines (flush=5s), so compressing it at once could leave them out.

// RotateSafetyCap is the `rotate` count rendered for a retention: 48 cuts a
// day — twice the hourly checks — floored at 100 and capped at 200000. A
// large cap costs logrotate nothing measurable (40-110 ms with 6,000 files).
func RotateSafetyCap(retentionDays int) int {
	c := retentionDays * 48
	if c < 100 {
		c = 100
	}
	if c > 200000 {
		c = 200000
	}
	return c
}

// RenderLogrotateConfig renders the stanza for access_raw.log and
// error_raw.log in dir. r should come from SystemSettings.EffectiveRawLogRotation.
func RenderLogrotateConfig(dir string, r model.RawLogRotation) string {
	compress := ""
	if r.Compress {
		compress = "    compress\n    delaycompress\n"
	}
	return fmt.Sprintf(`# Logrotate configuration for nginx-guard raw logs
# Auto-generated by API - do not edit. Driven by LogRotateScheduler:
# forced at 00:00, size/day check every hour. maxage is the retention;
# rotate is only a safety cap so hourly size cuts never delete inside it.

%[1]s/access_raw.log %[1]s/error_raw.log {
    daily
    maxsize %[2]dM
    maxage %[3]d
    rotate %[4]d
    missingok
    notifempty
    create 0644 nginx nginx
    sharedscripts
    dateext
    dateformat -%%Y%%m%%d-%%H%%M%%S
%[5]s    postrotate
        [ -f /var/run/nginx.pid ] && kill -USR1 $(cat /var/run/nginx.pid) 2>/dev/null || true
    endscript
}
`, dir, r.MaxSizeMB, r.RetentionDays, RotateSafetyCap(r.RetentionDays), compress)
}

// WriteLogrotateConfig renders the stanza and writes it to path through a
// temporary file and a rename, so a rotation copying the file at the same
// moment never installs half of it.
func WriteLogrotateConfig(path, dir string, r model.RawLogRotation) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".logrotate-*.tmp")
	if err != nil {
		return fmt.Errorf("write logrotate config: %w", err)
	}
	defer os.Remove(tmp.Name()) // no-op after the rename
	if _, err := tmp.WriteString(RenderLogrotateConfig(dir, r)); err != nil {
		tmp.Close()
		return fmt.Errorf("write logrotate config: %w", err)
	}
	if err := tmp.Chmod(0644); err != nil {
		tmp.Close()
		return fmt.Errorf("write logrotate config: %w", err)
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return fmt.Errorf("write logrotate config: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("write logrotate config: %w", err)
	}
	if err := os.Rename(tmp.Name(), path); err != nil {
		return fmt.Errorf("write logrotate config: %w", err)
	}
	return nil
}
